name: live_tracking
description: Live tracking for Mudrika mobile application
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_web3: ^0.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  mobile_scanner: ^3.0.0-beta.1
  provider: ^6.0.4
  syncfusion_flutter_maps: ^20.3.52
  url_launcher: ^6.1.6
  walletconnect_dart: ^0.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
